# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d4f24dbb6bc3741c7701716a26bd55ee90723d9364d0e468ddb7678f5598ff684e2305eaf137cd1934ccfcf9bceee99a819fcc8c7579b34859cdea846e9b8b7

test:
  secret_key_base: 42e492707869073d18cada47e907b2083891604a25a0aceeb320f4ce472f618d2d31c4d47521611827687f718e5e9e42e97d5caf39cf9dbf96d126191b5097c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
